config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#index'

  resources :users , only: [:show] do
    resources :albums
  end

  resources :albums do
    resources :images
  end

  resources :images do
    resources :comments
  end

  resources :images do
    resources :tags
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :images, dependent: :destroy
  belongs_to :user


  validates :name, :presence => true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_default, only: [:new, :create, :edit, :update, :destroy]

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    @album.user = @user

    if (@album.save)
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
    @image = Image.new
    @images = @album.images
  end

  def destroy
    @album = Album.find(params[:id])
    if current_user == @album.user
      @album.destroy
      redirect_to user_path(@user)
    else
      flash[:alert] = "This is not your album! This album belongs to #{@album.user.username}"
      redirect_to :back
    end
  end

  private
   def set_default
     @user = current_user

   end

   def album_params
     params.require(:album).permit(:name, :description)
   end

end

app/views/albums/_form.html.erb
<%= form_for [@user, @album] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

app/views/albums/new.html.erb
<%= render 'form' %>

app/views/albums/show.html.erb
<h2><%= @album.user.username %>'s <%= @album.name %></h2>
<% if current_user == @album.user %>
<%= link_to "Delete", album_path(@album), :data => {:confirm => "Are you sure?",
                                          method: :delete} %>
<%= render 'images/form' %>
<% end %>


<% @images.each do |image| %>
  <li>
    <%= link_to (image_tag image.picture.url(:thumb)),  image_path(image), id: "#{image.id}"%>
    <%= link_to image_path(image), :method => :delete do %>
        <span ><i class="glyphicon glyphicon-trash"></i></span>
     <% end %>
    </li>
<% end %>