config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'static_pages#index'

  resources :users , only: [:show] do
    resources :albums
  end

  resources :albums do
    resources :images
  end

  resources :images do
    resources :comments
  end

  resources :images do
    resources :tags
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :album
  has_many :comments
  belongs_to :user
  has_many :tags
  has_attached_file :picture, styles: { large: '1024 x 768>', display: '640 x 480>', thumb: '200 x 200>' }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  validates :picture, attachment_presence: true

  def next
    next_image = self.album.images.where("id > ?", self.id).first
    if next_image == nil
      next_image = self
    end
    next_image
  end

  def prev
    prev_image = self.album.images.where("id < ?", self.id).first
    if prev_image == nil
      prev_image = self
    end
    prev_image
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def create
    if params.has_key?(:image)
      @album = Album.find(params[:album_id])
      @image = Image.new(image_params)
      @image.album = @album
      @image.user = @album.user
      if @image.save
        flash[:notice] = "Image added"
        redirect_to album_path(@album)
      else
        flash[:notice] = "Image not added"
        redirect_to album_path(@album)
      end
    else
      flash[:notice] = "Please attach an image"
      redirect_to :back
    end
  end

  def show
    @tag = Tag.new
    @image = Image.find(params[:id])
    @users = User.untagged(@image)
    @album = @image.album
    @tags = @image.tags
    @comment = Comment.new
  end

  def destroy
    @image = Image.find(params[:id])
    if current_user == @image.user
      @image.destroy
      flash[:alert] = "Image gone forever!"
      redirect_to :back
    else
      flash[:alert] = "This is not your image! This image belongs to #{@image.user.username}"
      redirect_to :back
    end

  end

  private
  def image_params
    params.require(:image).permit(:picture)
  end

end

app/views/images/_form.html.erb
<%= render 'layouts/errors', :object => @image %>

<%= form_for [@album, @image] do |f| %>
<%= f.label :picture %><br>
<%= f.file_field :picture %>
<%= f.submit "Add Image" %>
<% end %>

app/views/images/show.html.erb
<%= link_to "Back to album", album_path(@album) %>
<br>
<%= image_tag @image.picture.url(:large) %>



<% if @image.comments.any? %>
  <ul>
    <% @image.comments.each do |comment| %>
      <li>
        <%= comment.user.username %>
        <%= comment.body %><br>
        <%= comment.created_at %>
        <% if current_user == comment.user %>
          <%= link_to 'Delete', image_comment_path(@image, comment), :method => :delete %>
          <%= link_to 'Edit', edit_image_comment_path(@image, comment)  %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

<%=link_to 'Previous', image_path(@image.prev) %>
<%=link_to 'Next', image_path(@image.next) %>

<% if @tags.any? %>
  <% @tags.each do |tag| %>
    <%= tag.user.username %>
  <% end %>
<% end %>

<p>
  Photo by: <%= @image.user.username %>
</p>
<%= render 'tags/form' %>
<%= render 'comments/form'%>